gradle version input

diff --git a/testautomation-action/action.yaml b/testautomation-action/action.yaml
--- a/testautomation-action/action.yaml
+++ b/testautomation-action/action.yaml
@@ -4,7 +4,7 @@ inputs:
   working-directory:
     type: string
     default: .
-    required: false 
+    required: false
 
   testautomation_build:
     required: false
@@ -15,7 +15,7 @@ inputs:
     type: string
   testautobranch:
     required: false
-    type: string     
+    type: string
   web-path:
     required: false
     type: string
@@ -34,15 +34,15 @@ inputs:
 
 runs:
   using: "composite"
-  steps:   
+  steps:
 
     - uses: actions/checkout@v3
       if: inputs.testautomation_build
       with:
-        repository: ${{ inputs.testautorepo }}        
+        repository: ${{ inputs.testautorepo }}
         fetch-depth: '0'
         ref: ${{ inputs.testautobranch }}
-        token: ${{ inputs.GHA_TOKEN }}   
+        token: ${{ inputs.GHA_TOKEN }}
 
     - name: Checkout main repository
       if: inputs.testautomation_build
@@ -52,7 +52,7 @@ runs:
         ref: ${{ github.ref }}
         token: ${{ inputs.GHA_TOKEN }}
         path: main-repo
-        fetch-depth: 0  
+        fetch-depth: 0
 
     - name: Print version.properties file
       if: inputs.testautomation_build
@@ -60,7 +60,7 @@ runs:
       shell: bash
 
     - name: Restore gradle.properties and setup
-      env:        
+      env:
         working-directory: "${{ inputs.working-directory }}"
       shell: bash
       run: |
@@ -77,6 +77,38 @@ runs:
         echo "Contents of gradle.properties after modification:"
         cat ~/.gradle/gradle.properties
 
+    - name: Extract gradle_version from additional file
+      working-directory: "${{ inputs.working-directory }}"
+      id: extract_gradle_version
+      shell: bash
+      run: |
+        if grep -q "gradle_version" ${{ inputs.additional_file }}; then
+          GRADLE_VERSION=$(grep 'gradle_version' ${{ inputs.additional_file }} | cut -d'=' -f2)
+          echo "GRADLE_VERSION=$GRADLE_VERSION" >> $GITHUB_ENV
+        else
+          echo "gradle_version not found in additional file" >&2
+          exit 1
+        fi
+
+    - name: Update gradle-wrapper.properties with new gradle_version
+      working-directory: "${{ inputs.working-directory }}"
+      shell: bash
+      run: |
+        GRADLE_PROPERTIES_PATH="${{ inputs.working-directory }}/${{ inputs.server-path }}/gradle/wrapper/gradle-wrapper.properties"
+        if [ -n "${{ env.GRADLE_VERSION }}" ]; then
+          NEW_DISTRIBUTION_URL="distributionUrl=https\://services.gradle.org/distributions/gradle-${{ env.GRADLE_VERSION }}-bin.zip"
+
+          if [ -f "$GRADLE_PROPERTIES_PATH" ]; then
+            sed -i "s|distributionUrl=.*|$NEW_DISTRIBUTION_URL|" "$GRADLE_PROPERTIES_PATH"
+            echo "Updated gradle-wrapper.properties:"
+            cat "$GRADLE_PROPERTIES_PATH"
+          else
+            echo "gradle-wrapper.properties not found!" >&2
+            exit 1
+          fi
+        else
+          echo "No gradle_version provided, skipping gradle-wrapper.properties update."
+        fi
     # - name: Check file existence
     #   if: inputs.repo_type == 'web'
     #   id: web_exists
@@ -97,7 +129,7 @@ runs:
     - name: Read FOUNDATION_VERSION from additional file
       # if: steps.web_exists.outputs.client_folder_exists == 'true'
       working-directory: "${{ inputs.working-directory }}"
-      id: extract_version        
+      id: extract_version
       shell: bash
       run: |
         if [ "${{ inputs.testautomation_build }}" == "true" ]; then
@@ -113,7 +145,7 @@ runs:
         fi
     - name: Check for package-lock.json and remove if exists
       # if: steps.web_exists.outputs.client_folder_exists == 'true'
-      working-directory: "${{ inputs.working-directory }}/${{ inputs.web-path }}"  
+      working-directory: "${{ inputs.working-directory }}/${{ inputs.web-path }}"
       shell: bash
       run: |
         if [ -f package-lock.json ]; then
@@ -123,14 +155,14 @@ runs:
           echo "No package-lock.json found."
         fi
 
-     
-    - name: Update @genesislcap dependencies 
+
+    - name: Update @genesislcap dependencies
       # if: steps.web_exists.outputs.client_folder_exists == 'true'
-      working-directory: "${{ inputs.working-directory }}/${{ inputs.web-path }}"  
-      shell: bash      
+      working-directory: "${{ inputs.working-directory }}/${{ inputs.web-path }}"
+      shell: bash
       run: |
-        NEW_VERSION="${{ steps.extract_version.outputs.foundation_version }}"    
-        echo "${{ inputs.working-directory }}/${{ inputs.web-path }}"       
+        NEW_VERSION="${{ steps.extract_version.outputs.foundation_version }}"
+        echo "${{ inputs.working-directory }}/${{ inputs.web-path }}"
         # Update @genesislcap dependencies across all objects in the package.json
         jq --arg version "$NEW_VERSION" '
           walk(
@@ -141,20 +173,20 @@ runs:
             else . end
           )
         ' package.json > package.json.tmp
-          
+
         # Move tmp file to overwrite the original package.json
           mv package.json.tmp package.json
         # Print the final updated package.json
         echo "Final updated package.json:"
         cat package.json
-      
+
     - name: Update @genesislcap versions in package.json
       # if: steps.web_exists.outputs.client_folder_exists == 'true'
       shell: bash
       working-directory: "./"
-      run: |          
+      run: |
         PACKAGE_JSON="${{ inputs.working-directory }}/${{ inputs.web-path }}/package.json"
-        INPUT_FILE="${{ inputs.working-directory }}/${{ inputs.additional_file }}"          
+        INPUT_FILE="${{ inputs.working-directory }}/${{ inputs.additional_file }}"
 
         # Read and update dependencies from version.properties
         while IFS= read -r line; do
