howto test

diff --git a/.github/workflows/build-docker-projects.yml b/.github/workflows/build-docker-projects.yml
--- a/.github/workflows/build-docker-projects.yml
+++ b/.github/workflows/build-docker-projects.yml
@@ -365,6 +365,98 @@ jobs:
             echo "No gradle_version provided, skipping gradle-wrapper.properties update."
           fi
 
+      - name: Read FOUNDATION_VERSION from additional file
+        # if: steps.web_exists.outputs.client_folder_exists == 'true'
+        working-directory: "${{ inputs.working-directory }}"
+        id: extract_version
+        shell: bash
+        run: |
+          if [ "${{ inputs.testautomation_build }}" == "true" ]; then
+            # Extract FOUNDATION_VERSION from the additional file
+            if grep -q "FOUNDATION_VERSION" ${{ inputs.working-directory }}/${{ inputs.additional_file }}; then
+              FOUNDATION_VERSION=$(grep 'FOUNDATION_VERSION' ${{ inputs.working-directory }}/${{ inputs.additional_file }} | cut -d'=' -f2)
+              echo "FOUNDATION_VERSION=$FOUNDATION_VERSION"
+              echo "::set-output name=foundation_version::$FOUNDATION_VERSION"
+            else
+              echo "FOUNDATION_VERSION not found in additional file"
+              exit 1
+            fi
+          fi
+
+      - name: Check for package-lock.json and remove if exists
+        working-directory: "${{ matrix.project }}/${{ inputs.web-path }}"
+        shell: bash
+        run: |
+          if [ -f package-lock.json ]; then
+            echo "Removing existing package-lock.json..."
+            rm package-lock.json
+          else
+            echo "No package-lock.json found."
+          fi
+
+      - name: Update @genesislcap dependencies
+        # if: steps.web_exists.outputs.client_folder_exists == 'true'
+        working-directory: "${{ matrix.project }}/${{ inputs.web-path }}"
+        shell: bash
+        run: |
+          NEW_VERSION="${{ steps.extract_version.outputs.foundation_version }}"
+          echo "${{ inputs.working-directory }}/${{ inputs.web-path }}"
+          # Update @genesislcap dependencies across all objects in the package.json
+          jq --arg version "$NEW_VERSION" '
+            walk(
+              if type == "object" then
+                with_entries(
+                  if (.key | startswith("@genesislcap")) then .value = $version else . end
+                )
+              else . end
+            )
+          ' package.json > package.json.tmp
+
+          # Move tmp file to overwrite the original package.json
+            mv package.json.tmp package.json
+          # Print the final updated package.json
+          echo "Final updated package.json:"
+          cat package.json
+
+      - name: Update @genesislcap versions in package.json
+        # if: steps.web_exists.outputs.client_folder_exists == 'true'
+        shell: bash
+        working-directory: "./"
+        run: |
+          PACKAGE_JSON="${{ matrix.project }}/${{ inputs.web-path }}/package.json"
+          INPUT_FILE="${{ inputs.working-directory }}/${{ inputs.additional_file }}"
+
+          # Read and update dependencies from version.properties
+          while IFS= read -r line; do
+            # Skip empty lines or comments
+            [[ -z "$line" || "$line" =~ ^# ]] && continue
+
+            # Process JSON-like entries
+            if [[ "$line" =~ ^\"(.+)\":\ \"(.+)\"$ ]]; then
+              key="${BASH_REMATCH[1]}"
+              value="${BASH_REMATCH[2]}"
+            else
+              # Process key=value pairs
+              key=$(echo "$line" | cut -d'=' -f1 | xargs)
+              value=$(echo "$line" | cut -d'=' -f2 | xargs)
+            fi
+
+            # Update the package.json file
+            jq --arg dep "$key" --arg version "$value" '
+              walk(
+                if type == "object" and has($dep) then
+                  .[$dep] = $version
+                else
+                  .
+                end
+              )
+            ' "$PACKAGE_JSON" > tmp.json && mv tmp.json "$PACKAGE_JSON"
+          done < "$INPUT_FILE"
+
+          # Print the updated package.json
+          echo "Updated package.json:"
+          cat "$PACKAGE_JSON"
+
       - name: Login to Genesis Container Registry
         uses: docker/login-action@v3
         with:
