Devops- adding SAST (#256)
* Update build-gradle-g8.yml

* Update build-gradle.yml

* Update build-gradle.yml

* Update build-gradle-g8.yml

* Update build-gradle.yml

* Update build-gradle-g8.yml

* Update build-gradle.yml

* Update build-gradle-g8.yml

* Update build-gradle-g8.yml

* Update build-gradle-g8.yml

* Update build-gradle-g8.yml

* Update build-gradle-g8.yml

* Update build-gradle-g8.yml

diff --git a/.github/workflows/build-gradle-g8.yml b/.github/workflows/build-gradle-g8.yml
--- a/.github/workflows/build-gradle-g8.yml
+++ b/.github/workflows/build-gradle-g8.yml
@@ -83,6 +83,10 @@ on:
         type: boolean
         required: false
         default: false
+      sast:
+        required: false
+        default: true
+        type: boolean
 
 
     secrets:
@@ -200,6 +204,31 @@ jobs:
         uses: genesislcap/appdev-workflows/read-dot-env@develop
         with:
           config-path: ${{ inputs.config-path }}
+
+      - name: Install Bearer CLI
+        if: inputs.sast
+        working-directory: "${{ inputs.working-directory }}"
+        run: |
+          curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
+          echo "PATH=$PWD/bin:$PATH" >> $GITHUB_ENV
+
+      - name: Run sast security scan (text report)
+        if: inputs.sast
+        working-directory: "${{ inputs.working-directory }}"
+        run: |
+          set +e
+          # --report=security is default, but added for clarity
+          # --exit-code 0 => never fail the job even if findings exist
+          bearer scan . --report=security --exit-code 0 | tee sast-report-${{ inputs.product_name }}-${{ github.run_number }}.sarif
+          set -e
+
+      # Upload the txt report as an artifact
+      - name: Upload sast Security Report
+        if: inputs.sast
+        uses: actions/upload-artifact@v4        
+        with:
+          name: sast-report-${{ inputs.product_name }}-${{ github.run_number }}
+          path: sast-report-${{ inputs.product_name }}-${{ github.run_number }}.sarif     
 
       - name: Build
         uses: gradle/gradle-build-action@v2
diff --git a/.github/workflows/build-gradle.yml b/.github/workflows/build-gradle.yml
--- a/.github/workflows/build-gradle.yml
+++ b/.github/workflows/build-gradle.yml
@@ -89,6 +89,10 @@ on:
         type: string
         description: Only used by the older version of genesisframework if SCOPE is used then REGISTRY_URL has to be passed
         required: false
+      sast:
+        required: false
+        default: true
+        type: boolean
 
     secrets:
       GRADLE_PROPERTIES:
@@ -176,7 +180,32 @@ jobs:
           cache-read-only: ${{ inputs.cache-read-only }}
           cache-write-only: ${{ inputs.cache-write-only }}
           cache-disabled: ${{ inputs.disable-cache }}
+      - name: Install Sast CLI
+        if: inputs.sast
+        working-directory: "${{ inputs.working-directory }}"
+        run: |
+          curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
+          echo "PATH=$PWD/bin:$PATH" >> $GITHUB_ENV
 
+      # Run scan and capture the human-readable "Security Report" into a txt file
+      - name: Run sast security scan (text report)
+        if: inputs.sast
+        working-directory: "${{ inputs.working-directory }}"
+        run: |
+          set +e
+          # --report=security is default, but added for clarity
+          # --exit-code 0 => never fail the job even if findings exist
+          bearer scan . --report=security --exit-code 0 | tee sast-report-${{ inputs.product_name }}-${{ github.run_number }}.SARIF
+          set -e
+
+      # Upload the txt report as an artifact
+      - name: Upload sast Security Report
+        if: inputs.sast
+        uses: actions/upload-artifact@v4        
+        with:
+          name: sast-report-${{ inputs.product_name }}-${{ github.run_number }}
+          path: sast-report-${{ inputs.product_name }}-${{ github.run_number }}.SARIF
+          
       - name: Server Build
         run: ./gradlew build --stacktrace -PpushToCache=${{ inputs.push-to-artifactory-cache }} -PdisableRemoteCache=${{ !inputs.use-artifactory-cache }} ${{ inputs.server-build-gradle-arguments }} ${{ env.CACHE_OPTS }}
         working-directory: "${{ inputs.working-directory }}/${{ inputs.server-path }}"
