test gradle project

diff --git a/.github/workflows/build-docker-projects.yml b/.github/workflows/build-docker-projects.yml
--- a/.github/workflows/build-docker-projects.yml
+++ b/.github/workflows/build-docker-projects.yml
@@ -16,6 +16,14 @@ on:
         type: string
         default: stable
         description: Key to allow job to runs in paralell overnight
+      working-directory:
+        type: string
+        default: .
+        required: false
+      additional_file:
+        required: false
+        type: string
+        default: 'main-repo/.github/workflows/version.properties'  
 
     secrets:
       GRADLE_PROPERTIES:
@@ -65,7 +73,17 @@ jobs:
           repository: genesislcap/platform-howto
           fetch-depth: '0'
           ref: consolidated-branch
-          token: ${{ env.GHA_TOKEN }}    
+          token: ${{ env.GHA_TOKEN }}   
+
+      - name: Checkout main repository
+        # if: inputs.testautomation_build
+        uses: actions/checkout@v3
+        with:
+          repository: genesislcap/platform-qa-automation
+          ref: ${{ github.ref }}
+          token: ${{ secrets.GHA_TOKEN }}
+          path: main-repo
+          fetch-depth: 0 
 
       - name: Setup jq
         uses: dcarbone/install-jq-action@v2.1.0
@@ -112,6 +130,44 @@ jobs:
             echo "projects=${changed_projects}" >> $GITHUB_OUTPUT
 
           fi
+
+      - name: Restore gradle.properties and setup        
+        working-directory: "${{ inputs.working-directory }}"
+        shell: bash
+        run: |          
+
+          # Set file permissions
+          # sudo chmod +x ./gradlew
+          # sudo chmod +x ./${{ inputs.server-path }}/gradlew
+          # sudo chmod -R +rx ./${{ inputs.server-path }}/
+          
+
+          # Append contents of additional file to gradle.properties based on condition
+          # if [ "${{ inputs.testautomation_build }}" == "true" ]; then
+            echo "Appending contents of additional file to gradle.properties"
+            if [ -f "${{ inputs.working-directory }}/${{ inputs.additional_file }}" ]; then
+              cat ${{ inputs.additional_file }} >> ~/.gradle/gradle.properties
+            else
+              echo "Additional file not found: ${{ inputs.additional_file }}" >&2
+            fi
+          # fi
+
+          # Print the gradle.properties file for verification
+          echo "Contents of gradle.properties after modification:"
+          cat ~/.gradle/gradle.properties
+          
+          cat ~/.gradle/gradle.properties >>  ./gradle.properties
+          
+          # if [ -z "${{ inputs.repo-name }}" ]; then
+          #   echo "REPO_NAME=$(echo '${{ github.event.repository.name }}' | cut -d'-' -f1)" >> $GITHUB_ENV
+          # else
+          #   echo "REPO_NAME=${{ inputs.repo-name }}" >> $GITHUB_ENV
+          # fi
+          
+          # RELEASE_VERSION=$(echo "${{ inputs.version }}" | sed 's/\//-/g')
+          # echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
+          # sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts
+
       - name: Job summary
         run: |
           echo -e "# 🔨 Build information" >> $GITHUB_STEP_SUMMARY
