qatest automation changes

diff --git a/.github/workflows/build-gradle.yml b/.github/workflows/build-gradle.yml
--- a/.github/workflows/build-gradle.yml
+++ b/.github/workflows/build-gradle.yml
@@ -115,31 +115,21 @@ jobs:
     runs-on: [ appdev-selfhosted-al2023 ]
     steps:
       - name: Checkout code      
-        if: ${{ !inputs.testautomation_build }}
+        # if: ${{ !inputs.testautomation_build }}
         uses: actions/checkout@v3
         with:
           fetch-depth: '0'
           ref: ${{ inputs.branch }}   
 
-      - name: testautomation_build steps 
-        if: inputs.testautomation_build
-        uses: genesislcap/appdev-workflows/testautomation-web-action@qaautomation
-        with:
-          web-path: ${{ inputs.web-path }}
-          testautomation_build: ${{ inputs.testautomation_build }}
-          testautorepo: ${{ inputs.testautorepo }}
-          testautobranch: ${{ inputs.testautobranch }}
-          additional_file: ${{ inputs.additional_file }} 
-          repo_type: "server"        
-          GHA_TOKEN: ${{secrets.GHA_TOKEN}}
+      
 
-      - uses: actions/checkout@v3
-        if: inputs.testautomation_build
-        with:
-          repository: ${{ inputs.testautorepo }}        
-          fetch-depth: '0'
-          ref: ${{ inputs.testautobranch }}
-          token: ${{ env.GHA_TOKEN }}          
+      # - uses: actions/checkout@v3
+      #   if: inputs.testautomation_build
+      #   with:
+      #     repository: ${{ inputs.testautorepo }}        
+      #     fetch-depth: '0'
+      #     ref: ${{ inputs.testautobranch }}
+      #     token: ${{ env.GHA_TOKEN }}          
       
       - name: Set up JDK
         uses: actions/setup-java@v2
@@ -147,19 +137,19 @@ jobs:
           java-version: ${{ inputs.java_version }}
           distribution: 'adopt'
 
-      - name: Checkout main repository
-        if: inputs.testautomation_build
-        uses: actions/checkout@v3
-        with:
-          repository: genesislcap/platform-qa-automation
-          ref: ${{ github.ref }}
-          token: ${{ secrets.GHA_TOKEN }}
-          path: main-repo
-          fetch-depth: 0 
+      # - name: Checkout main repository
+      #   if: inputs.testautomation_build
+      #   uses: actions/checkout@v3
+      #   with:
+      #     repository: genesislcap/platform-qa-automation
+      #     ref: ${{ github.ref }}
+      #     token: ${{ secrets.GHA_TOKEN }}
+      #     path: main-repo
+      #     fetch-depth: 0 
           
-      - name: Print version.properties file
-        if: inputs.testautomation_build
-        run: cat main-repo/.github/workflows/version.properties
+      # - name: Print version.properties file
+      #   if: inputs.testautomation_build
+      #   run: cat main-repo/.github/workflows/version.properties
         
       - name: Restore gradle.properties and setup
         env:
@@ -189,16 +179,16 @@ jobs:
           sudo chmod +x ./${{ inputs.server-path }}/gradlew
           sudo chmod -R +rx ./${{ inputs.server-path }}/
           
-          if [ "${{ inputs.testautomation_build }}" == "true" ]; then
-            echo "Appending contents of additional file to gradle.properties"
-            if [ -f "${{ inputs.working-directory }}/${{ inputs.additional_file }}" ]; then
-              cat ${{ inputs.additional_file }} >> ~/.gradle/gradle.properties
-            else
-              echo "Additional file not found: ${{ inputs.additional_file }}" >&2
-            fi
-          fi
-          echo "Contents of gradle.properties after modification:"
-          cat ~/.gradle/gradle.properties
+          # if [ "${{ inputs.testautomation_build }}" == "true" ]; then
+          #   echo "Appending contents of additional file to gradle.properties"
+          #   if [ -f "${{ inputs.working-directory }}/${{ inputs.additional_file }}" ]; then
+          #     cat ${{ inputs.additional_file }} >> ~/.gradle/gradle.properties
+          #   else
+          #     echo "Additional file not found: ${{ inputs.additional_file }}" >&2
+          #   fi
+          # fi
+          # echo "Contents of gradle.properties after modification:"
+          # cat ~/.gradle/gradle.properties
           
           cat ~/.gradle/gradle.properties >>  ./gradle.properties
           
@@ -211,7 +201,18 @@ jobs:
           RELEASE_VERSION=$(echo "${{ inputs.version }}" | sed 's/\//-/g')
           echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
           sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts
-
+      - name: testautomation_build steps 
+        if: inputs.testautomation_build
+        uses: genesislcap/appdev-workflows/testautomation-web-action@qaautomation
+        with:
+          web-path: ${{ inputs.web-path }}
+          testautomation_build: ${{ inputs.testautomation_build }}
+          testautorepo: ${{ inputs.testautorepo }}
+          testautobranch: ${{ inputs.testautobranch }}
+          additional_file: ${{ inputs.additional_file }} 
+          repo_type: "server"        
+          GHA_TOKEN: ${{secrets.GHA_TOKEN}}
+          
       - name: Server Build        
         uses: gradle/gradle-build-action@v2
         with:
