deploy pipeline for qa qutomation

diff --git a/.github/workflows/build-gradle.yml b/.github/workflows/build-gradle.yml
--- a/.github/workflows/build-gradle.yml
+++ b/.github/workflows/build-gradle.yml
@@ -77,30 +77,30 @@ on:
       testautobranch:
         required: false
         type: string
-      GENESIS_VERSION:
-        required: false
-        type: string
-      AUTH_VERSION:
-        required: false
-        type: string
-      GENESIS_NOTIFY:
-        required: false
-        type: string
-      NOTIFY_VERSION:
-        required: false
-        type: string
-      FIX_VERSION:
-        required: false
-        type: string
-      FIlESERVER_VERSION:
-        required: false
-        type: string
-      EXPORT_VERSION:
-        required: false
-        type: string
-      DEPLOYPLUGIN_VERSION:
-        required: false
-        type: string
+      # GENESIS_VERSION:
+      #   required: false
+      #   type: string
+      # AUTH_VERSION:
+      #   required: false
+      #   type: string
+      # GENESIS_NOTIFY:
+      #   required: false
+      #   type: string
+      # NOTIFY_VERSION:
+      #   required: false
+      #   type: string
+      # FIX_VERSION:
+      #   required: false
+      #   type: string
+      # FIlESERVER_VERSION:
+      #   required: false
+      #   type: string
+      # EXPORT_VERSION:
+      #   required: false
+      #   type: string
+      # DEPLOYPLUGIN_VERSION:
+      #   required: false
+      #   type: string
       FOUNDATION_VERSION:
         required: false
         type: string
@@ -108,6 +108,10 @@ on:
         required: false
         type: string
         default: 'client/web'
+      additional_file:
+        required: false
+        type: string
+        default: '/opt/actions-runner/_work/platform-qa-automation/platform-qa-automation/.github/workflows/version.properties'
       
 
     secrets:
@@ -153,42 +157,7 @@ jobs:
           ref: ${{ inputs.testautobranch }}
           token: ${{ env.GHA_TOKEN }}
 
-      - name: Set genesisVersion in gradle.properties
-        if: inputs.testautomation_build
-        working-directory: "${{ inputs.working-directory }}/${{ inputs.server-path }}"
-        run: |
-          if [ -n "${{ inputs.GENESIS_VERSION }}" ]; then
-            sed -i 's/^genesisVersion=.*/genesisVersion=${{ inputs.GENESIS_VERSION }}/' gradle.properties
-          fi
-          if [ -n "${{ inputs.AUTH_VERSION }}" ]; then
-            sed -i 's/^authVersion=.*/authVersion=${{ inputs.AUTH_VERSION }}/' gradle.properties
-          fi
-          if [ -n "${{ inputs.GENESIS_NOTIFY }}" ]; then
-            sed -i 's/^genesisNotify=.*/genesisNotify=${{ inputs.GENESIS_NOTIFY }}/' gradle.properties
-          fi
-          if [ -n "${{ inputs.NOTIFY_VERSION }}" ]; then
-            sed -i 's/^genesisNotify=.*/genesisNotify=${{ inputs.NOTIFY_VERSION }}/' gradle.properties
-          fi
-          if [ -n "${{ inputs.FIX_VERSION }}" ]; then
-            sed -i 's/^fixVersion=.*/fixVersion=${{ inputs.FIX_VERSION }}/' gradle.properties
-          fi
-          if [ -n "${{ inputs.FIlESERVER_VERSION }}" ]; then
-            sed -i 's/^fileserverVersion=.*/fileserverVersion=${{ inputs.FIlESERVER_VERSION }}/' gradle.properties
-          fi
-          if [ -n "${{ inputs.EXPORT_VERSION }}" ]; then
-            sed -i 's/^exportVersion=.*/exportVersion=${{ inputs.EXPORT_VERSION }}/' gradle.properties
-          fi
-          if [ -n "${{ inputs.DEPLOYPLUGIN_VERSION }}" ]; then
-            sed -i 's/^deployPluginVersion=.*/deployPluginVersion=${{ inputs.DEPLOYPLUGIN_VERSION }}/' gradle.properties
-          fi
-          
-      - name: Print gradle.properties
-        if: inputs.testautomation_build
-        working-directory: "${{ inputs.working-directory }}/${{ inputs.server-path }}"
-        run: |
-          echo "Contents of gradle.properties after modification:"
-          cat gradle.properties
-          
+      
       - name: Set up JDK
         uses: actions/setup-java@v2
         with:
@@ -203,6 +172,8 @@ jobs:
         run: |
           mkdir -p ~/.gradle/
           echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
+          
+          # Write initial properties
           echo "genesisArtifactoryUser=${{ secrets.JFROG_USERNAME }}" > ~/.gradle/gradle.properties
           echo "genesisArtifactoryPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties
 
@@ -216,15 +187,31 @@ jobs:
 
           echo "genesis-home=../.genesis-home" >> ~/.gradle/gradle.properties
           echo "deploy-plugin-mode=local" >> ~/.gradle/gradle.properties
+
+          # Set file permissions
           sudo chmod +x ./gradlew
           sudo chmod +x ./${{ inputs.server-path }}/gradlew
           sudo chmod -R +rx ./${{ inputs.server-path }}/
+
+          # Append contents of another file to gradle.properties
+          if [ -f "${{ inputs.additional_file }}" ]; then
+            cat ${{ inputs.additional_file }} >> ~/.gradle/gradle.properties
+          else
+            echo "Additional file not found: ${{ inputs.additional_file }}" >&2
+          fi
+
+          # Print the gradle.properties file for verification
+          echo "Contents of gradle.properties after modification:"
+          cat ~/.gradle/gradle.properties
+          
           cat ~/.gradle/gradle.properties >>  ./gradle.properties
+          
           if [ -z "${{ inputs.repo-name }}" ]; then
             echo "REPO_NAME=$(echo '${{ github.event.repository.name }}' | cut -d'-' -f1)" >> $GITHUB_ENV
           else
             echo "REPO_NAME=${{ inputs.repo-name }}" >> $GITHUB_ENV
           fi
+          
           RELEASE_VERSION=$(echo "${{ inputs.version }}" | sed 's/\//-/g')
           echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
           sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts
