qatest automation changes

diff --git a/.github/workflows/build-gradle-g8.yml b/.github/workflows/build-gradle-g8.yml
--- a/.github/workflows/build-gradle-g8.yml
+++ b/.github/workflows/build-gradle-g8.yml
@@ -68,6 +68,32 @@ on:
         description: Only used by the older version of genesisframework if SCOPE is used then REGISTRY_URL has to be passed
         required: false
 
+      testautomation_build:
+        required: false
+        default: false
+        type: boolean
+      testautorepo:
+        required: false
+        type: string
+      testautobranch:
+        required: false
+        type: string
+
+      server-path:
+        required: false
+        type: string
+        default: 'server'
+      FOUNDATION_VERSION:
+        required: false
+        type: string
+      web-path:
+        required: false
+        type: string
+        default: 'client'
+      additional_file:
+        required: false
+        type: string
+        default: 'main-repo/.github/workflows/version.properties'
 
     secrets:
       GRADLE_PROPERTIES:
@@ -84,21 +110,34 @@ on:
         required: false
       JFROG_NPM_AUTH_TOKEN:
         required: false
+      GHA_TOKEN:
+        required: true
         
 
 env:
   NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}
   DISTRIBUTION_DIR: ${{ inputs.distribution_dir || format('{0}-distribution', inputs.product_name) }}
+  GHA_TOKEN: ${{secrets.GHA_TOKEN}}
 
 # A workflow run is called from the devops appdev-workflow repos
 jobs:
   build-server:
     runs-on: [ appdev-selfhosted-al2023 ]
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout code      
+        if: ${{ !inputs.testautomation_build }}
+        uses: actions/checkout@v3
         with:
           fetch-depth: '0'
-          ref: ${{ inputs.branch }}
+          ref: ${{ inputs.branch }}     
+
+      - uses: actions/checkout@v3
+        if: inputs.testautomation_build
+        with:
+          repository: ${{ inputs.testautorepo }}        
+          fetch-depth: '0'
+          ref: ${{ inputs.testautobranch }}
+          token: ${{ env.GHA_TOKEN }}
 
       - name: Set up JDK
         uses: actions/setup-java@v2
@@ -121,6 +160,23 @@ jobs:
           scope: ${{ inputs.SCOPE }}
         env:
           NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}
+      - name: Setup npm registry for @genesislcap
+        run: |
+          echo "Using npmjs.com for @genesislcap scoped packages"
+          npm config set @genesislcap:registry https://registry.npmjs.org/
+          npm config list
+        env:
+          NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}
+      
+      
+      - name: Checkout main repository
+        if: inputs.testautomation_build
+        uses: actions/checkout@v3
+        with:
+          repository: genesislcap/platform-qa-automation
+          ref: ${{ github.ref }}
+          token: ${{ secrets.GHA_TOKEN }}
+          path: main-repo
 
       - name: Restore gradle.properties and setup
         env:
@@ -145,6 +201,20 @@ jobs:
           echo "deploy-plugin-mode=local" >> ~/.gradle/gradle.properties
           sudo chmod +x ./gradlew
           sudo chmod +x ./server/gradlew
+
+          # Append contents of additional file to gradle.properties based on condition
+          if [ "${{ inputs.testautomation_build }}" == "true" ]; then
+            echo "Appending contents of additional file to gradle.properties"
+            if [ -f "${{ inputs.working-directory }}/${{ inputs.additional_file }}" ]; then
+              cat ${{ inputs.additional_file }} >> ~/.gradle/gradle.properties
+            else
+              echo "Additional file not found: ${{ inputs.additional_file }}" >&2
+            fi
+          fi
+
+          # Print the gradle.properties file for verification
+          echo "Contents of gradle.properties after modification:"
+          cat ~/.gradle/gradle.properties
 
           cat ~/.gradle/gradle.properties >>  ./gradle.properties
           if [ -z "${{ inputs.repo-name }}" ]; then
@@ -171,10 +241,102 @@ jobs:
           echo "//genesisglobal.jfrog.io/artifactory/api/npm/github-packages/:email=jenkins@genesis.global" >> $RUNNER_TEMP/.npmrc
           echo "//genesisglobal.jfrog.io/artifactory/api/npm/github-packages/:always-auth=true" >> $RUNNER_TEMP/.npmrc
 
+      - name: Read FOUNDATION_VERSION from additional file
+        if: inputs.testautomation_build
+        working-directory: "${{ inputs.working-directory }}"
+        id: extract_version        
+        shell: bash
+        run: |
+          if [ "${{ inputs.testautomation_build }}" == "true" ]; then
+            # Extract FOUNDATION_VERSION from the additional file
+            if grep -q "FOUNDATION_VERSION" ${{ inputs.working-directory }}/${{ inputs.additional_file }}; then
+              FOUNDATION_VERSION=$(grep 'FOUNDATION_VERSION' ${{ inputs.working-directory }}/${{ inputs.additional_file }} | cut -d'=' -f2)
+              echo "FOUNDATION_VERSION=$FOUNDATION_VERSION"
+              echo "::set-output name=foundation_version::$FOUNDATION_VERSION"
+            else
+              echo "FOUNDATION_VERSION not found in additional file"
+              exit 1
+            fi
+          fi
+
+      - name: Check for package-lock.json and remove if exists
+        if: inputs.testautomation_build
+        working-directory: "${{ inputs.working-directory }}/${{ inputs.web-path }}"
+        run: |
+          if [ -f package-lock.json ]; then
+            echo "Removing existing package-lock.json..."
+            rm package-lock.json
+          else
+            echo "No package-lock.json found."
+          fi
+
+      - name: Update @genesislcap dependencies
+        if: inputs.testautomation_build
+        working-directory: "${{ inputs.working-directory }}/${{ inputs.web-path }}"
+        run: |
+          NEW_VERSION="${{ steps.extract_version.outputs.foundation_version }}"          
+          # Update @genesislcap dependencies across all objects in the package.json
+          jq --arg version "$NEW_VERSION" '
+            walk(
+              if type == "object" then
+                with_entries(
+                  if (.key | startswith("@genesislcap")) then .value = $version else . end
+                )
+              else . end
+            )
+          ' package.json > package.json.tmp
+          
+          # Move tmp file to overwrite the original package.json
+          mv package.json.tmp package.json
+          # Print the final updated package.json
+          echo "Final updated package.json:"
+          cat package.json
+          
+      - name: Update @genesislcap versions in package.json
+        if: inputs.testautomation_build
+        shell: bash
+        working-directory: "./"
+        run: |
+          # Define variables        
+          
+          PACKAGE_JSON="${{ inputs.working-directory }}/${{ inputs.web-path }}/package.json"
+          INPUT_FILE="${{ inputs.working-directory }}/${{ inputs.additional_file }}"
+
+          # Read and update dependencies from version.properties
+          while IFS= read -r line; do
+            # Skip empty lines or comments
+            [[ -z "$line" || "$line" =~ ^# ]] && continue
+
+            # Process JSON-like entries
+            if [[ "$line" =~ ^\"(.+)\":\ \"(.+)\"$ ]]; then
+              key="${BASH_REMATCH[1]}"
+              value="${BASH_REMATCH[2]}"
+            else
+              # Process key=value pairs
+              key=$(echo "$line" | cut -d'=' -f1 | xargs)
+              value=$(echo "$line" | cut -d'=' -f2 | xargs)
+            fi
+
+            # Update the package.json file
+            jq --arg dep "$key" --arg version "$value" '
+              walk(
+                if type == "object" and has($dep) then
+                  .[$dep] = $version
+                else
+                  .
+                end
+              )
+            ' "$PACKAGE_JSON" > tmp.json && mv tmp.json "$PACKAGE_JSON"
+          done < "$INPUT_FILE"
+
+          # Print the updated package.json
+          echo "Updated package.json:"
+          cat "$PACKAGE_JSON"
+
       - name: Server Build
         uses: gradle/gradle-build-action@v2
         with:
-          arguments: build --no-build-cache --stacktrace -Pversion=${{ env.RELEASE_VERSION }} -PpushToCache=${{ inputs.push-to-artifactory-cache }} -PdisableRemoteCache=${{ !inputs.use-artifactory-cache }} ${{ inputs.server-build-gradle-arguments }}
+          arguments: build --no-build-cache --stacktrace -Pversion=${{ env.RELEASE_VERSION }} -PpushToCache=${{ inputs.push-to-artifactory-cache }} -PdisableRemoteCache=${{ !inputs.use-artifactory-cache }} ${{ inputs.server-build-gradle-arguments }}-PuseDevRepo=true
           build-root-directory: "${{ inputs.working-directory }}"
           cache-disabled: true
 
@@ -194,7 +356,7 @@ jobs:
       - name: Upload Test Reports
         uses: actions/upload-artifact@v4
         with:
-          name: test-reports
+          name: test-reports-${{ inputs.product_name }}
           path: "${{ inputs.working-directory }}/test-results"
         if: always()
         
diff --git a/.github/workflows/ghrunner-build-web.yml b/.github/workflows/ghrunner-build-web.yml
--- a/.github/workflows/ghrunner-build-web.yml
+++ b/.github/workflows/ghrunner-build-web.yml
@@ -19,6 +19,28 @@ on:
         required: false
         type: boolean
         default: true
+      
+      testautomation_build:
+        required: false
+        default: false
+        type: boolean
+      testautorepo:
+        required: false
+        type: string
+      testautobranch:
+        required: false
+        type: string
+      version:
+        required: false
+        type: string
+      working-directory:
+        type: string
+        default: .
+        required: false
+      additional_file:
+        required: false
+        type: string
+        default: 'main-repo/.github/workflows/version.properties'  
 
     secrets:
       JFROG_USERNAME:
@@ -35,19 +57,24 @@ on:
         required: false
       SLACK_WEBHOOK:
         required: false
+      GHA_TOKEN:
+        required: true          
+
 
 env:
   REPO_NAME: ${{ inputs.repo_name }}
+  GHA_TOKEN: ${{secrets.GHA_TOKEN}}
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   build:
-    name: Steps to build the artifact and upload it to jfrog
+    name: Web build
     env:
       JFROG_USERNAME: ${{secrets.JFROG_USERNAME}}
       JFROG_EMAIL: ${{secrets.JFROG_EMAIL}}
       JFROG_PASSWORD: ${{secrets.JFROG_PASSWORD}}
       JFROG_NPM_AUTH_TOKEN: ${{secrets.JFROG_NPM_AUTH_TOKEN}}
+      GHA_TOKEN: ${{secrets.GHA_TOKEN}}
     runs-on: appdev-selfhosted-al2023
 
     strategy:
@@ -55,17 +82,31 @@ jobs:
         node-version: [16.x]
 
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout code
+        if: ${{ !inputs.testautomation_build }}
+        uses: actions/checkout@v3
         with:
           fetch-depth: '0'
+          ref: ${{ inputs.branch }}     
+
+      - uses: actions/checkout@v3
+        if: inputs.testautomation_build
+        with:
+          repository: ${{ inputs.testautorepo }}        
+          fetch-depth: '0'
+          ref: ${{ inputs.testautobranch }}
+          token: ${{ env.GHA_TOKEN }} 
 
       - name: Env Setup
         run:  |
               echo "PRODUCT_BASE=$(pwd)" >> $GITHUB_ENV
               echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
               echo "PRODUCT_NAME=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)" >> $GITHUB_ENV #NOTE: only works with SSH repo urls + will cause issues with bny_investments
-              echo "OUTPUT=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)-web-$(git describe --tags).zip" >> $GITHUB_ENV
-
+              if [ "${{ inputs.testautomation_build }}" == "true" ]; then
+                echo "OUTPUT=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)-web-${{ inputs.version }}.zip" >> $GITHUB_ENV
+              else
+                echo "OUTPUT=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)-web-$(git describe --tags).zip" >> $GITHUB_ENV
+              fi
       - name: Env Setup for nightly build
         if: ${{ inputs.branch == 'develop' ||  inputs.branch == 'main' ||  inputs.branch == 'master' }}
         run:  |
@@ -75,6 +116,108 @@ jobs:
         if: ${{ inputs.product_name }}
         run: |
               echo "PRODUCT_NAME=${{ inputs.product_name }}" >> $GITHUB_ENV #NOTE: only for those that are not following a standard naming convention
+
+      - name: Checkout main repository
+        if: inputs.testautomation_build
+        uses: actions/checkout@v3
+        with:
+          repository: genesislcap/platform-qa-automation
+          ref: ${{ github.ref }}
+          token: ${{ secrets.GHA_TOKEN }}
+          path: main-repo
+
+      # Step to extract FOUNDATION_VERSION from additional_file
+      - name: Read FOUNDATION_VERSION from additional file
+        if: inputs.testautomation_build
+        working-directory: "${{ inputs.working-directory }}"
+        id: extract_version        
+        shell: bash
+        run: |
+          if [ "${{ inputs.testautomation_build }}" == "true" ]; then
+            # Extract FOUNDATION_VERSION from the additional file
+            if grep -q "FOUNDATION_VERSION" ${{ inputs.working-directory }}/${{ inputs.additional_file }}; then
+              FOUNDATION_VERSION=$(grep 'FOUNDATION_VERSION' ${{ inputs.working-directory }}/${{ inputs.additional_file }} | cut -d'=' -f2)
+              echo "FOUNDATION_VERSION=$FOUNDATION_VERSION"
+              echo "::set-output name=foundation_version::$FOUNDATION_VERSION"
+            else
+              echo "FOUNDATION_VERSION not found in additional file"
+              exit 1
+            fi
+          fi
+      
+      - name: Check for package-lock.json and remove if exists
+        if: inputs.testautomation_build   
+        working-directory: ${{ inputs.working-directory }}/packages/apps/${{ env.PRODUCT_NAME }} 
+        run: |
+          if [ -f package-lock.json ]; then
+            echo "Removing existing package-lock.json..."
+            rm package-lock.json
+          else
+            echo "No package-lock.json found."
+          fi
+
+     
+      - name: Update @genesislcap dependencies 
+        if: inputs.testautomation_build   
+        working-directory: ${{ inputs.working-directory }}/packages/apps/${{ env.PRODUCT_NAME }}       
+        run: |
+          NEW_VERSION="${{ steps.extract_version.outputs.foundation_version }}"          
+          # Update @genesislcap dependencies across all objects in the package.json
+          jq --arg version "$NEW_VERSION" '
+            walk(
+              if type == "object" then
+                with_entries(
+                  if (.key | startswith("@genesislcap")) then .value = $version else . end
+                )
+              else . end
+            )
+          ' package.json > package.json.tmp
+          
+          # Move tmp file to overwrite the original package.json
+          mv package.json.tmp package.json
+          # Print the final updated package.json
+          echo "Final updated package.json:"
+          cat package.json
+      
+      - name: Update @genesislcap versions in package.json
+        if: inputs.testautomation_build   
+        shell: bash
+        working-directory: "./"
+        run: |
+          
+          PACKAGE_JSON="${{ inputs.working-directory }}/packages/apps/${{ env.PRODUCT_NAME }}/package.json"
+          INPUT_FILE="${{ inputs.working-directory }}/${{ inputs.additional_file }}"          
+
+          # Read and update dependencies from version.properties
+          while IFS= read -r line; do
+            # Skip empty lines or comments
+            [[ -z "$line" || "$line" =~ ^# ]] && continue
+
+            # Process JSON-like entries
+            if [[ "$line" =~ ^\"(.+)\":\ \"(.+)\"$ ]]; then
+              key="${BASH_REMATCH[1]}"
+              value="${BASH_REMATCH[2]}"
+            else
+              # Process key=value pairs
+              key=$(echo "$line" | cut -d'=' -f1 | xargs)
+              value=$(echo "$line" | cut -d'=' -f2 | xargs)
+            fi
+
+            # Update the package.json file
+            jq --arg dep "$key" --arg version "$value" '
+              walk(
+                if type == "object" and has($dep) then
+                  .[$dep] = $version
+                else
+                  .
+                end
+              )
+            ' "$PACKAGE_JSON" > tmp.json && mv tmp.json "$PACKAGE_JSON"
+          done < "$INPUT_FILE"
+
+          # Print the updated package.json
+          echo "Updated package.json:"
+          cat "$PACKAGE_JSON"
 
       - name: Sonar Setup
         run:  |
@@ -106,7 +249,7 @@ jobs:
           NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}
 
       - name: Build
-        working-directory: packages/apps/${{ env.PRODUCT_NAME }}
+        working-directory: ${{ inputs.working-directory }}/packages/apps/${{ env.PRODUCT_NAME }}
         run: npm run build
 
       - name: Lint Check
@@ -120,7 +263,7 @@ jobs:
       - name: Upload lint artifact
         uses: actions/upload-artifact@v4
         with:
-          name: Lint errors
+          name: Lint errors-${{ env.PRODUCT_NAME }}
           path: lint-output.txt
 
       - name: Package and Publish
