data pft backup

diff --git a/.github/workflows/build-docker-projects.yml b/.github/workflows/build-docker-projects.yml
--- a/.github/workflows/build-docker-projects.yml
+++ b/.github/workflows/build-docker-projects.yml
@@ -20,6 +20,10 @@ on:
         type: string
         default: .
         required: false
+      server-path:
+        required: false
+        type: string
+        default: 'server'
       additional_file:
         required: false
         type: string
@@ -75,15 +79,15 @@ jobs:
           ref: consolidated-branch
           token: ${{ env.GHA_TOKEN }}
 
-      - name: Checkout main repository
-        # if: inputs.testautomation_build
-        uses: actions/checkout@v3
-        with:
-          repository: genesislcap/platform-qa-automation
-          ref: ${{ github.ref }}
-          token: ${{ secrets.GHA_TOKEN }}
-          path: main-repo
-          fetch-depth: 0
+      # - name: Checkout main repository
+      #   # if: inputs.testautomation_build
+      #   uses: actions/checkout@v3
+      #   with:
+      #     repository: genesislcap/platform-qa-automation
+      #     ref: ${{ github.ref }}
+      #     token: ${{ secrets.GHA_TOKEN }}
+      #     path: main-repo
+      #     fetch-depth: 0
 
       - name: Setup jq
         uses: dcarbone/install-jq-action@v2.1.0
@@ -131,54 +135,54 @@ jobs:
 
           fi
 
-      - name: Restore gradle.properties and setup
-        working-directory: "${{ inputs.working-directory }}"
-        shell: bash
-        run: |
-          echo "Listing all files in the working-directory:"
-          pwd
-          ls -la
+      # - name: Restore gradle.properties and setup
+      #   working-directory: "${{ inputs.working-directory }}"
+      #   shell: bash
+      #   run: |
+      #     echo "Listing all files in the working-directory:"
+      #     pwd
+      #     ls -la
 
-          mkdir -p ~/.gradle/
-          echo "COMPLETED0"
-          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
-          echo "COMPLETED1"
-          # Write initial properties
-          echo "genesisArtifactoryUser=${{ secrets.JFROG_USERNAME }}" > ~/.gradle/gradle.properties
-          echo "genesisArtifactoryPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties
-          echo "COMPLETED2"
+      #     mkdir -p ~/.gradle/
+      #     echo "COMPLETED0"
+      #     echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
+      #     echo "COMPLETED1"
+      #     # Write initial properties
+      #     echo "genesisArtifactoryUser=${{ secrets.JFROG_USERNAME }}" > ~/.gradle/gradle.properties
+      #     echo "genesisArtifactoryPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties
+      #     echo "COMPLETED2"
 
-          # Set file permissions
-          # sudo chmod +x ./gradlew
-          # sudo chmod +x ./${{ inputs.server-path }}/gradlew
-          # sudo chmod -R +rx ./${{ inputs.server-path }}/
+      #     # Set file permissions
+      #     # sudo chmod +x ./gradlew
+      #     # sudo chmod +x ./${{ inputs.server-path }}/gradlew
+      #     # sudo chmod -R +rx ./${{ inputs.server-path }}/
 
 
-          # Append contents of additional file to gradle.properties based on condition
-          # if [ "${{ inputs.testautomation_build }}" == "true" ]; then
-            echo "Appending contents of additional file to gradle.properties"
-            if [ -f "${{ inputs.working-directory }}/${{ inputs.additional_file }}" ]; then
-              cat ${{ inputs.additional_file }} >> ~/.gradle/gradle.properties
-            else
-              echo "Additional file not found: ${{ inputs.additional_file }}" >&2
-            fi
-          # fi
+      #     # Append contents of additional file to gradle.properties based on condition
+      #     # if [ "${{ inputs.testautomation_build }}" == "true" ]; then
+      #       echo "Appending contents of additional file to gradle.properties"
+      #       if [ -f "${{ inputs.working-directory }}/${{ inputs.additional_file }}" ]; then
+      #         cat ${{ inputs.additional_file }} >> ~/.gradle/gradle.properties
+      #       else
+      #         echo "Additional file not found: ${{ inputs.additional_file }}" >&2
+      #       fi
+      #     # fi
 
-          # Print the gradle.properties file for verification
-          echo "Contents of gradle.properties after modification:"
-          cat ~/.gradle/gradle.properties
+      #     # Print the gradle.properties file for verification
+      #     echo "Contents of gradle.properties after modification:"
+      #     cat ~/.gradle/gradle.properties
 
-          cat ~/.gradle/gradle.properties >>  ./gradle.properties
+      #     cat ~/.gradle/gradle.properties >>  ./gradle.properties
 
-          # if [ -z "${{ inputs.repo-name }}" ]; then
-          #   echo "REPO_NAME=$(echo '${{ github.event.repository.name }}' | cut -d'-' -f1)" >> $GITHUB_ENV
-          # else
-          #   echo "REPO_NAME=${{ inputs.repo-name }}" >> $GITHUB_ENV
-          # fi
+      #     # if [ -z "${{ inputs.repo-name }}" ]; then
+      #     #   echo "REPO_NAME=$(echo '${{ github.event.repository.name }}' | cut -d'-' -f1)" >> $GITHUB_ENV
+      #     # else
+      #     #   echo "REPO_NAME=${{ inputs.repo-name }}" >> $GITHUB_ENV
+      #     # fi
 
-          # RELEASE_VERSION=$(echo "${{ inputs.version }}" | sed 's/\//-/g')
-          # echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
-          # sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts
+      #     # RELEASE_VERSION=$(echo "${{ inputs.version }}" | sed 's/\//-/g')
+      #     # echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
+      #     # sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts
 
       - name: Job summary
         run: |
@@ -291,6 +295,50 @@ jobs:
           # RELEASE_VERSION=$(echo "${{ inputs.version }}" | sed 's/\//-/g')
           # echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
           # sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts
+
+      - name: Extract gradle_version from additional file
+        working-directory: "${{ inputs.working-directory }}"
+        id: extract_gradle_version
+        shell: bash
+        run: |
+          GRADLE_PROPERTIES_FILE="${{ inputs.working-directory }}/${{ inputs.additional_file }}"
+
+          if grep -q "gradle_version" "$GRADLE_PROPERTIES_FILE"; then
+            GRADLE_VERSION=$(grep 'gradle_version' "$GRADLE_PROPERTIES_FILE" | cut -d'=' -f2)
+            echo "GRADLE_VERSION=$GRADLE_VERSION" >> $GITHUB_ENV
+          else
+            echo "gradle_version not found in additional file, skipping update."
+            echo "GRADLE_VERSION=" >> $GITHUB_ENV
+          fi
+
+      - name: Update gradle-wrapper.properties with new gradle_version
+        working-directory: ${{ matrix.project }}
+        shell: bash
+        run: |
+          GRADLE_PROPERTIES_PATH="${{ inputs.working-directory }}/${{ inputs.server-path }}/gradle/wrapper/gradle-wrapper.properties"
+          DEFAULT_GRADLE_PROPERTIES_PATH="${{ inputs.working-directory }}/gradle/wrapper/gradle-wrapper.properties"
+          if [ -n "${{ env.GRADLE_VERSION }}" ]; then
+            NEW_DISTRIBUTION_URL="distributionUrl=https\://services.gradle.org/distributions/gradle-${{ env.GRADLE_VERSION }}-bin.zip"
+
+            if [ -f "$DEFAULT_GRADLE_PROPERTIES_PATH" ]; then
+              sed -i "s|distributionUrl=.*|$NEW_DISTRIBUTION_URL|" "$DEFAULT_GRADLE_PROPERTIES_PATH"
+              echo "Updated gradle-wrapper.properties:"
+              cat "$DEFAULT_GRADLE_PROPERTIES_PATH"
+            else
+              echo "gradle-wrapper.properties not found!" >&2
+              exit 1
+            fi
+            if [ -f "$GRADLE_PROPERTIES_PATH" ]; then
+              sed -i "s|distributionUrl=.*|$NEW_DISTRIBUTION_URL|" "$GRADLE_PROPERTIES_PATH"
+              echo "Updated gradle-wrapper.properties:"
+              cat "$GRADLE_PROPERTIES_PATH"
+            else
+              echo "gradle-wrapper.properties not found!" >&2
+              exit 1
+            fi
+          else
+            echo "No gradle_version provided, skipping gradle-wrapper.properties update."
+          fi
 
       - name: Login to Genesis Container Registry
         uses: docker/login-action@v3
