call jenkins job to deploy pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,23 +50,31 @@ jobs:
           # export ANSIBLE_STDOUT_CALLBACK=debug
           # python3 ~/selfserve/scripts/deployEnv.py ${{ inputs.action }} ${{ inputs.file_name }}
       
-      - name: Fix curl Installation
+      - name: Fix Curl Installation
         run: |
-          # Remove any conflicting curl packages
-          sudo dnf remove -y curl curl-minimal
-          
-          # Clean DNF cache
-          sudo dnf clean all
-          
-          # Update DNF metadata
-          sudo dnf update -y
-          
-          # Install curl
-          sudo dnf install -y curl
-          
-          # Check curl installation
-          curl --version
-          
+          # Check if curl is already installed
+          if ! command -v curl &> /dev/null; then
+            echo "curl not found, attempting to install."
+            
+            # Clean DNF cache and update metadata
+            sudo dnf clean all
+            sudo dnf update -y
+            
+            # Install curl from the default repository or use an alternate source if needed
+            sudo dnf install -y curl || {
+              echo "Failed to install curl using default method. Trying alternative installation.";
+              
+              # Use an alternative method to install curl if the default fails
+              sudo dnf install -y epel-release
+              sudo dnf install -y curl
+            }
+
+            # Verify curl installation
+            curl --version
+          else
+            echo "curl is already installed."
+          fi
+
       - name: Install Dependencies
         run: |
           sudo dnf install -y curl
