Update ghrunner-build-web-node10.yml

diff --git a/.github/workflows/ghrunner-build-web-node10.yml b/.github/workflows/ghrunner-build-web-node10.yml
--- a/.github/workflows/ghrunner-build-web-node10.yml
+++ b/.github/workflows/ghrunner-build-web-node10.yml
@@ -119,9 +119,14 @@ jobs:
         run: |
           echo "LINT_CHECK=$(grep -Fxq "lint" $(cat package.json))" >> $GITHUB_ENV
           
-      - name: ESLint
-        if: ${{env.LINT_CHECK==1 }} 
-        run: npm run lint:eslint:all
+      - name: Run ESLint
+        run: npm run lint > lint-output.txt || echo "Linting completed with errors"
+        
+      - name: Upload lint artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: Lint errors
+          path: lint-output.txt
           
       - name: Package and Publish
         run:  |
