deploy pipeline for qa qutomation

diff --git a/.github/workflows/ghrunner-build-mono-web.yml b/.github/workflows/ghrunner-build-mono-web.yml
--- a/.github/workflows/ghrunner-build-mono-web.yml
+++ b/.github/workflows/ghrunner-build-mono-web.yml
@@ -24,10 +24,11 @@ on:
         type: string
       version:
         required: false
+        type: string 
+      working-directory:
         type: string
-      FOUNDATION_VERSION:
-        required: false
-        type: string      
+        default: .
+        required: false     
 
     secrets:
       JFROG_USERNAME:
@@ -79,11 +80,40 @@ jobs:
           ref: ${{ inputs.testautobranch }}
           token: ${{ env.GHA_TOKEN }}
 
-      - name: Update @genesislcap/foundation dependencies 
-        if: inputs.FOUNDATION_VERSION
-        working-directory: ./client/web       
+      
+      - name: Checkout main repository
+        if: inputs.testautomation_build
+        uses: actions/checkout@v3
+        with:
+          repository: genesislcap/platform-qa-automation
+          ref: DCD-1785-2
+          token: ${{ secrets.GHA_TOKEN }}
+          path: main-repo
+
+      # Step to extract FOUNDATION_VERSION from additional_file
+      - name: Read FOUNDATION_VERSION from additional file
+        if: inputs.testautomation_build
+        working-directory: "${{ inputs.working-directory }}"
+        id: extract_version        
+        shell: bash
         run: |
-          NEW_VERSION="${{ inputs.FOUNDATION_VERSION }}"
+          if [ "${{ inputs.testautomation_build }}" == "true" ]; then
+            # Extract FOUNDATION_VERSION from the additional file
+            if grep -q "FOUNDATION_VERSION" ${{ inputs.working-directory }}/${{ inputs.additional_file }}; then
+              FOUNDATION_VERSION=$(grep 'FOUNDATION_VERSION' ${{ inputs.working-directory }}/${{ inputs.additional_file }} | cut -d'=' -f2)
+              echo "FOUNDATION_VERSION=$FOUNDATION_VERSION"
+              echo "::set-output name=foundation_version::$FOUNDATION_VERSION"
+            else
+              echo "FOUNDATION_VERSION not found in additional file"
+              exit 1
+            fi
+          fi
+
+      - name: Update @genesislcap/foundation dependencies 
+        if: inputs.testautomation_build
+        working-directory: ./client/web 
+        run: |
+          NEW_VERSION="${{ steps.extract_version.outputs.foundation_version }}"
           # Update only @genesislcap/foundation dependencies
           jq --arg version "$NEW_VERSION" '
             .dependencies |= with_entries(
@@ -96,12 +126,11 @@ jobs:
           echo "Updated @genesislcap/foundation-* dependencies to version $NEW_VERSION."
 
       - name: Print updated package.json
-        if: inputs.FOUNDATION_VERSION
-        working-directory: ./client/web
+        if: inputs.testautomation_build
+        working-directory: ./client/web 
         run: |
           echo "Updated package.json:"
           cat package.json
-
 
       - name: Configure Node ${{ matrix.node-version }}
         uses: actions/setup-node@v2
