qatest automation changes

diff --git a/.github/workflows/ghrunner-build-web.yml b/.github/workflows/ghrunner-build-web.yml
--- a/.github/workflows/ghrunner-build-web.yml
+++ b/.github/workflows/ghrunner-build-web.yml
@@ -30,6 +30,10 @@ on:
       testautobranch:
         required: false
         type: string
+      web-path:
+        required: false
+        type: string
+        default: 'packages/apps'
       version:
         required: false
         type: string
@@ -89,13 +93,13 @@ jobs:
           fetch-depth: '0'
           ref: ${{ inputs.branch }}     
 
-      - uses: actions/checkout@v3
-        if: inputs.testautomation_build
-        with:
-          repository: ${{ inputs.testautorepo }}        
-          fetch-depth: '0'
-          ref: ${{ inputs.testautobranch }}
-          token: ${{ env.GHA_TOKEN }} 
+      # - uses: actions/checkout@v3
+      #   if: inputs.testautomation_build
+      #   with:
+      #     repository: ${{ inputs.testautorepo }}        
+      #     fetch-depth: '0'
+      #     ref: ${{ inputs.testautobranch }}
+      #     token: ${{ env.GHA_TOKEN }} 
 
       - name: Env Setup
         run:  |
@@ -114,109 +118,119 @@ jobs:
         run: |
               echo "PRODUCT_NAME=${{ inputs.product_name }}" >> $GITHUB_ENV #NOTE: only for those that are not following a standard naming convention
 
-      - name: Checkout main repository
-        if: inputs.testautomation_build
-        uses: actions/checkout@v3
-        with:
-          repository: genesislcap/platform-qa-automation
-          ref: ${{ github.ref }}
-          token: ${{ secrets.GHA_TOKEN }}
-          path: main-repo
+      # - name: Checkout main repository
+      #   if: inputs.testautomation_build
+      #   uses: actions/checkout@v3
+      #   with:
+      #     repository: genesislcap/platform-qa-automation
+      #     ref: ${{ github.ref }}
+      #     token: ${{ secrets.GHA_TOKEN }}
+      #     path: main-repo
 
       # Step to extract FOUNDATION_VERSION from additional_file
-      - name: Read FOUNDATION_VERSION from additional file
-        if: inputs.testautomation_build
-        working-directory: "${{ inputs.working-directory }}"
-        id: extract_version        
-        shell: bash
-        run: |
-          if [ "${{ inputs.testautomation_build }}" == "true" ]; then
-            # Extract FOUNDATION_VERSION from the additional file
-            if grep -q "FOUNDATION_VERSION" ${{ inputs.working-directory }}/${{ inputs.additional_file }}; then
-              FOUNDATION_VERSION=$(grep 'FOUNDATION_VERSION' ${{ inputs.working-directory }}/${{ inputs.additional_file }} | cut -d'=' -f2)
-              echo "FOUNDATION_VERSION=$FOUNDATION_VERSION"
-              echo "::set-output name=foundation_version::$FOUNDATION_VERSION"
-            else
-              echo "FOUNDATION_VERSION not found in additional file"
-              exit 1
-            fi
-          fi
+      # - name: Read FOUNDATION_VERSION from additional file
+      #   if: inputs.testautomation_build
+      #   working-directory: "${{ inputs.working-directory }}"
+      #   id: extract_version        
+      #   shell: bash
+      #   run: |
+      #     if [ "${{ inputs.testautomation_build }}" == "true" ]; then
+      #       # Extract FOUNDATION_VERSION from the additional file
+      #       if grep -q "FOUNDATION_VERSION" ${{ inputs.working-directory }}/${{ inputs.additional_file }}; then
+      #         FOUNDATION_VERSION=$(grep 'FOUNDATION_VERSION' ${{ inputs.working-directory }}/${{ inputs.additional_file }} | cut -d'=' -f2)
+      #         echo "FOUNDATION_VERSION=$FOUNDATION_VERSION"
+      #         echo "::set-output name=foundation_version::$FOUNDATION_VERSION"
+      #       else
+      #         echo "FOUNDATION_VERSION not found in additional file"
+      #         exit 1
+      #       fi
+      #     fi
       
-      - name: Check for package-lock.json and remove if exists
-        if: inputs.testautomation_build   
-        working-directory: ${{ inputs.working-directory }}/packages/apps/${{ env.PRODUCT_NAME }} 
-        run: |
-          if [ -f package-lock.json ]; then
-            echo "Removing existing package-lock.json..."
-            rm package-lock.json
-          else
-            echo "No package-lock.json found."
-          fi
+      # - name: Check for package-lock.json and remove if exists
+      #   if: inputs.testautomation_build   
+      #   working-directory: ${{ inputs.working-directory }}/packages/apps/${{ env.PRODUCT_NAME }} 
+      #   run: |
+      #     if [ -f package-lock.json ]; then
+      #       echo "Removing existing package-lock.json..."
+      #       rm package-lock.json
+      #     else
+      #       echo "No package-lock.json found."
+      #     fi
 
      
-      - name: Update @genesislcap dependencies 
-        if: inputs.testautomation_build   
-        working-directory: ${{ inputs.working-directory }}/packages/apps/${{ env.PRODUCT_NAME }}       
-        run: |
-          NEW_VERSION="${{ steps.extract_version.outputs.foundation_version }}"          
-          # Update @genesislcap dependencies across all objects in the package.json
-          jq --arg version "$NEW_VERSION" '
-            walk(
-              if type == "object" then
-                with_entries(
-                  if (.key | startswith("@genesislcap")) then .value = $version else . end
-                )
-              else . end
-            )
-          ' package.json > package.json.tmp
+      # - name: Update @genesislcap dependencies 
+      #   if: inputs.testautomation_build   
+      #   working-directory: ${{ inputs.working-directory }}/${{ inputs.web-path }}/${{ env.PRODUCT_NAME }}      
+      #   run: |
+      #     NEW_VERSION="${{ steps.extract_version.outputs.foundation_version }}"          
+      #     # Update @genesislcap dependencies across all objects in the package.json
+      #     jq --arg version "$NEW_VERSION" '
+      #       walk(
+      #         if type == "object" then
+      #           with_entries(
+      #             if (.key | startswith("@genesislcap")) then .value = $version else . end
+      #           )
+      #         else . end
+      #       )
+      #     ' package.json > package.json.tmp
           
-          # Move tmp file to overwrite the original package.json
-          mv package.json.tmp package.json
-          # Print the final updated package.json
-          echo "Final updated package.json:"
-          cat package.json
+      #     # Move tmp file to overwrite the original package.json
+      #     mv package.json.tmp package.json
+      #     # Print the final updated package.json
+      #     echo "Final updated package.json:"
+      #     cat package.json
       
-      - name: Update @genesislcap versions in package.json
-        if: inputs.testautomation_build   
-        shell: bash
-        working-directory: "./"
-        run: |
+      # - name: Update @genesislcap versions in package.json
+      #   if: inputs.testautomation_build   
+      #   shell: bash
+      #   working-directory: "./"
+      #   run: |
           
-          PACKAGE_JSON="${{ inputs.working-directory }}/packages/apps/${{ env.PRODUCT_NAME }}/package.json"
-          INPUT_FILE="${{ inputs.working-directory }}/${{ inputs.additional_file }}"          
+      #     PACKAGE_JSON="${{ inputs.working-directory }}/${{ inputs.web-path }}"/${{ env.PRODUCT_NAME }}/package.json"
+      #     INPUT_FILE="${{ inputs.working-directory }}/${{ inputs.additional_file }}"          
 
-          # Read and update dependencies from version.properties
-          while IFS= read -r line; do
-            # Skip empty lines or comments
-            [[ -z "$line" || "$line" =~ ^# ]] && continue
+      #     # Read and update dependencies from version.properties
+      #     while IFS= read -r line; do
+      #       # Skip empty lines or comments
+      #       [[ -z "$line" || "$line" =~ ^# ]] && continue
 
-            # Process JSON-like entries
-            if [[ "$line" =~ ^\"(.+)\":\ \"(.+)\"$ ]]; then
-              key="${BASH_REMATCH[1]}"
-              value="${BASH_REMATCH[2]}"
-            else
-              # Process key=value pairs
-              key=$(echo "$line" | cut -d'=' -f1 | xargs)
-              value=$(echo "$line" | cut -d'=' -f2 | xargs)
-            fi
+      #       # Process JSON-like entries
+      #       if [[ "$line" =~ ^\"(.+)\":\ \"(.+)\"$ ]]; then
+      #         key="${BASH_REMATCH[1]}"
+      #         value="${BASH_REMATCH[2]}"
+      #       else
+      #         # Process key=value pairs
+      #         key=$(echo "$line" | cut -d'=' -f1 | xargs)
+      #         value=$(echo "$line" | cut -d'=' -f2 | xargs)
+      #       fi
 
-            # Update the package.json file
-            jq --arg dep "$key" --arg version "$value" '
-              walk(
-                if type == "object" and has($dep) then
-                  .[$dep] = $version
-                else
-                  .
-                end
-              )
-            ' "$PACKAGE_JSON" > tmp.json && mv tmp.json "$PACKAGE_JSON"
-          done < "$INPUT_FILE"
+      #       # Update the package.json file
+      #       jq --arg dep "$key" --arg version "$value" '
+      #         walk(
+      #           if type == "object" and has($dep) then
+      #             .[$dep] = $version
+      #           else
+      #             .
+      #           end
+      #         )
+      #       ' "$PACKAGE_JSON" > tmp.json && mv tmp.json "$PACKAGE_JSON"
+      #     done < "$INPUT_FILE"
 
-          # Print the updated package.json
-          echo "Updated package.json:"
-          cat "$PACKAGE_JSON"
+      #     # Print the updated package.json
+      #     echo "Updated package.json:"
+      #     cat "$PACKAGE_JSON"
 
-
+      - name: testautomation_build steps 
+        if: inputs.testautomation_build
+        uses: genesislcap/appdev-workflows/testautomation-web-action@qaautomation
+        with:
+          web-path: ${{ inputs.web-path }}/${{ env.PRODUCT_NAME }}
+          testautomation_build: ${{ inputs.testautomation_build }}
+          testautorepo: ${{ inputs.testautorepo }}
+          testautobranch: ${{ inputs.testautobranch }}
+          additional_file: ${{ inputs.additional_file }} 
+          repo_type: "web"        
+          GHA_TOKEN: ${{secrets.GHA_TOKEN}}
 
        
       - name: Sonar Setup
