test tam

diff --git a/.github/workflows/ghrunner-build-site-tam-nightly-build.yml b/.github/workflows/ghrunner-build-site-tam-nightly-build.yml
--- a/.github/workflows/ghrunner-build-site-tam-nightly-build.yml
+++ b/.github/workflows/ghrunner-build-site-tam-nightly-build.yml
@@ -115,85 +115,87 @@ jobs:
              ls -larth rpm/
              ls -larth rpm/rpm/legacy
              TARGET_FOLDER="tam2-site-specific-arden"
-              for i in "$TARGET_FOLDER"/*
+              for i in ./*
               do
                 echo "Web version is"
-                if [ -d "$i/snt" ]
-                then
-                    echo "Web version is"
-                    CLIENT_DIR=$i
-                    CLIENT_NAME=$(echo $i | sed "s/${{ env.REPO_NAME }}\-//g")
-                    [[ $(grep "web_version" $i/snt/product.yml) ]] && WEB_VERSION=$(grep "web_version" $(find $i/snt/ -name product.yml) | awk -F ':' '{print $2}' | sed 's/ //g')
-                    echo "Web version is : $WEB_VERSION"
-                    [[ ! -z "$WEB_VERSION" ]] && WEB_VERSION="${{ inputs.branch }}"
-                    cat $i/snt/product.yml
-                    mkdir "$CLIENT_NAME"_server_downloads && mkdir "$CLIENT_NAME"_web_downloads
-                    echo "Change location to the client specific src directory-->" && cd ${{ env.PRODUCT_BASE }}/$i/src
-                    zip -r ${{ env.PRODUCT_BASE }}/$i/${{ env.OUTPUT }} site-specific/*
-                    curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.PRODUCT_NAME }}/site/$CLIENT_NAME/${{env.OUTPUT}}" -T ${{ env.PRODUCT_BASE }}/$i/${{env.OUTPUT}}
-                    cp ${{ env.PRODUCT_BASE }}/$i/${{env.OUTPUT}} ${{env.PRODUCT_BASE}}/"$CLIENT_NAME"_server_downloads
-                    cd ${{ env.PRODUCT_BASE }}
-                    echo " Download modules into server_downloads folder in : $CLIENT_NAME_server_downloads "
-                    if [[ $(grep -c "genesis_modules" $i/snt/product.yml) -ge 1 ]]; then
-                        set +x -e
-                        echo "$(sed -e '1,/genesis_modules/d'  < $i/snt/product.yml | grep "^  - { ")" > /tmp/"$CLIENT_NAME"_edited_product.yml
-                        while read line
-                          do
-                            wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" -P ${{env.PRODUCT_BASE}}/"$CLIENT_NAME"_server_downloads https://genesisglobal.jfrog.io/artifactory/product/$((grep -oP '(?<=name:).*?(?=,)' <<< $line)|awk '$1=$1')/server/genesisproduct-$((grep -oP '(?<=name:).*?(?=,)' <<< $line) | awk '$1=$1')-$((grep -oP '(?<=version: )[^ ]*' <<< $line)|awk '$1=$1' )-bin.zip
-                          done < /tmp/"$CLIENT_NAME"_edited_product.yml
-                        echo "Modules required for $CLIENT_NAME required are-->" && cat /tmp/"$CLIENT_NAME"_edited_product.yml
-                        rm /tmp/"$CLIENT_NAME"_edited_product.yml
-                    fi
-                    cd ${{ env.PRODUCT_BASE }}
-                    if [ "$WEB_VERSION" == "" ]; then
-                      echo "Product Name: ${{ env.PRODUCT_NAME }} does not have a requirement for web, creating an empty zipped up folder for deployment requirements"
-                      cd "$CLIENT_NAME"_web_downloads
-                      touch temp
-                      if [ -n "${{ inputs.nginx-conf }}" ]; then
-                        cp "${GITHUB_WORKSPACE}/${{ inputs.nginx-conf }}" ./nginx.conf
+                if [ "$i" = "./tam2-site-specific-arden" ]; then
+                  if [ -d "$i/snt" ]
+                  then
+                      echo "Web version is"
+                      CLIENT_DIR=$i
+                      CLIENT_NAME=$(echo $i | sed "s/${{ env.REPO_NAME }}\-//g")
+                      [[ $(grep "web_version" $i/snt/product.yml) ]] && WEB_VERSION=$(grep "web_version" $(find $i/snt/ -name product.yml) | awk -F ':' '{print $2}' | sed 's/ //g')
+                      echo "Web version is : $WEB_VERSION"
+                      [[ ! -z "$WEB_VERSION" ]] && WEB_VERSION="${{ inputs.branch }}"
+                      cat $i/snt/product.yml
+                      mkdir "$CLIENT_NAME"_server_downloads && mkdir "$CLIENT_NAME"_web_downloads
+                      echo "Change location to the client specific src directory-->" && cd ${{ env.PRODUCT_BASE }}/$i/src
+                      zip -r ${{ env.PRODUCT_BASE }}/$i/${{ env.OUTPUT }} site-specific/*
+                      curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.PRODUCT_NAME }}/site/$CLIENT_NAME/${{env.OUTPUT}}" -T ${{ env.PRODUCT_BASE }}/$i/${{env.OUTPUT}}
+                      cp ${{ env.PRODUCT_BASE }}/$i/${{env.OUTPUT}} ${{env.PRODUCT_BASE}}/"$CLIENT_NAME"_server_downloads
+                      cd ${{ env.PRODUCT_BASE }}
+                      echo " Download modules into server_downloads folder in : $CLIENT_NAME_server_downloads "
+                      if [[ $(grep -c "genesis_modules" $i/snt/product.yml) -ge 1 ]]; then
+                          set +x -e
+                          echo "$(sed -e '1,/genesis_modules/d'  < $i/snt/product.yml | grep "^  - { ")" > /tmp/"$CLIENT_NAME"_edited_product.yml
+                          while read line
+                            do
+                              wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" -P ${{env.PRODUCT_BASE}}/"$CLIENT_NAME"_server_downloads https://genesisglobal.jfrog.io/artifactory/product/$((grep -oP '(?<=name:).*?(?=,)' <<< $line)|awk '$1=$1')/server/genesisproduct-$((grep -oP '(?<=name:).*?(?=,)' <<< $line) | awk '$1=$1')-$((grep -oP '(?<=version: )[^ ]*' <<< $line)|awk '$1=$1' )-bin.zip
+                            done < /tmp/"$CLIENT_NAME"_edited_product.yml
+                          echo "Modules required for $CLIENT_NAME required are-->" && cat /tmp/"$CLIENT_NAME"_edited_product.yml
+                          rm /tmp/"$CLIENT_NAME"_edited_product.yml
                       fi
-                      tar czvf /tmp/genesis_${{ env.PRODUCT_NAME }}_web.tar.gz *
-                      cd ../"$CLIENT_NAME"_server_downloads
-                    else
-                      #download web
-                      cd "$CLIENT_NAME"_web_downloads
-                      echo "Product Name: ${{ env.PRODUCT_NAME }} required web to be installed ..."
-                      wget --user=${{ secrets.JFROG_USERNAME }} --password="${{ secrets.JFROG_PASSWORD }}" -P ${{ env.PRODUCT_BASE }}/"$CLIENT_NAME"_web_downloads https://genesisglobal.jfrog.io/artifactory/product/"${{ env.PRODUCT_NAME }}"/web/"${{ env.PRODUCT_NAME }}"-web-"$WEB_VERSION".zip
+                      cd ${{ env.PRODUCT_BASE }}
+                      if [ "$WEB_VERSION" == "" ]; then
+                        echo "Product Name: ${{ env.PRODUCT_NAME }} does not have a requirement for web, creating an empty zipped up folder for deployment requirements"
+                        cd "$CLIENT_NAME"_web_downloads
+                        touch temp
+                        if [ -n "${{ inputs.nginx-conf }}" ]; then
+                          cp "${GITHUB_WORKSPACE}/${{ inputs.nginx-conf }}" ./nginx.conf
+                        fi
+                        tar czvf /tmp/genesis_${{ env.PRODUCT_NAME }}_web.tar.gz *
+                        cd ../"$CLIENT_NAME"_server_downloads
+                      else
+                        #download web
+                        cd "$CLIENT_NAME"_web_downloads
+                        echo "Product Name: ${{ env.PRODUCT_NAME }} required web to be installed ..."
+                        wget --user=${{ secrets.JFROG_USERNAME }} --password="${{ secrets.JFROG_PASSWORD }}" -P ${{ env.PRODUCT_BASE }}/"$CLIENT_NAME"_web_downloads https://genesisglobal.jfrog.io/artifactory/product/"${{ env.PRODUCT_NAME }}"/web/"${{ env.PRODUCT_NAME }}"-web-"$WEB_VERSION".zip
+                        unzip \*.zip
+                        if [ -n "${{ inputs.nginx-conf }}" ]; then
+                          cp "${GITHUB_WORKSPACE}/${{ inputs.nginx-conf }}" ./nginx.conf
+                        fi
+                        tar czvf /tmp/genesis_${{ env.PRODUCT_NAME }}_web.tar.gz *
+                        cd ../"$CLIENT_NAME"_server_downloads
+                      fi
+                      cp -r ${{env.PRODUCT_BASE}}/distros/*   ${{env.PRODUCT_BASE}}/"$CLIENT_NAME"_server_downloads/
                       unzip \*.zip
-                      if [ -n "${{ inputs.nginx-conf }}" ]; then
-                        cp "${GITHUB_WORKSPACE}/${{ inputs.nginx-conf }}" ./nginx.conf
+                      rm *.zip
+                      tar czvf /tmp/genesis_${{env.PRODUCT_NAME}}_package.tar.gz *
+                      pwd
+                      ls -larth
+                      cp ${{ env.PRODUCT_BASE }}/rpm/rpm/legacy/pom.xml pom.xml
+                      sed -i "s/PRODUCT/$PRODUCT_NAME/g" pom.xml
+                      if [ $(test -f /tmp/install.sh && echo 1 || echo 0) -eq 1  ]
+                      then
+                        rm /tmp/install.sh
                       fi
-                      tar czvf /tmp/genesis_${{ env.PRODUCT_NAME }}_web.tar.gz *
-                      cd ../"$CLIENT_NAME"_server_downloads
-                    fi
-                    cp -r ${{env.PRODUCT_BASE}}/distros/*   ${{env.PRODUCT_BASE}}/"$CLIENT_NAME"_server_downloads/
-                    unzip \*.zip
-                    rm *.zip
-                    tar czvf /tmp/genesis_${{env.PRODUCT_NAME}}_package.tar.gz *
-                    pwd
-                    ls -larth
-                    cp ${{ env.PRODUCT_BASE }}/rpm/rpm/legacy/pom.xml pom.xml
-                    sed -i "s/PRODUCT/$PRODUCT_NAME/g" pom.xml
-                    if [ $(test -f /tmp/install.sh && echo 1 || echo 0) -eq 1  ]
-                    then
-                      rm /tmp/install.sh
-                    fi
-                    cp ${{ env.PRODUCT_BASE }}/rpm/rpm/legacy/install.sh /tmp/install.sh
-                    sed -i "s/product_name/$PRODUCT_NAME/g" /tmp/install.sh
-                    if [ "$PRODUCT_NAME" == "wm_aqs" ]
-                    then
-                       sed -i "s/genesisUser/aqs/g" /tmp/install.sh
+                      cp ${{ env.PRODUCT_BASE }}/rpm/rpm/legacy/install.sh /tmp/install.sh
+                      sed -i "s/product_name/$PRODUCT_NAME/g" /tmp/install.sh
+                      if [ "$PRODUCT_NAME" == "wm_aqs" ]
+                      then
+                        sed -i "s/genesisUser/aqs/g" /tmp/install.sh
+                      else
+                        sed -i "s/genesisUser/$(echo $PRODUCT_NAME | sed -E 's/[0-9]+//g')/g" /tmp/install.sh
+                      fi
+                      source ~/.bashrc
+                      mvn versions:set -DnewVersion=$VERSION
+                      mvn rpm:rpm
+                      cd target/rpm/genesis-${PRODUCT_NAME}/RPMS/x86_64/${RPM_NAME} && echo "$(ls -lart)"
+                      curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.PRODUCT_NAME }}/rpm/$CLIENT_NAME/" -T *.rpm
                     else
-                       sed -i "s/genesisUser/$(echo $PRODUCT_NAME | sed -E 's/[0-9]+//g')/g" /tmp/install.sh
+                      echo "$i is not a directory or does not have a snt folder in it"
                     fi
-                    source ~/.bashrc
-                    mvn versions:set -DnewVersion=$VERSION
-                    mvn rpm:rpm
-                    cd target/rpm/genesis-${PRODUCT_NAME}/RPMS/x86_64/${RPM_NAME} && echo "$(ls -lart)"
-                    curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.PRODUCT_NAME }}/rpm/$CLIENT_NAME/" -T *.rpm
-                  else
-                    echo "$i is not a directory or does not have a snt folder in it"
-                  fi
+                fi
               cd ${{ env.PRODUCT_BASE }}
               echo "reset the web version for the next loop"
               WEB_VERSION=""
