test execution

diff --git a/.github/workflows/jenkins-deploy.yml b/.github/workflows/jenkins-deploy.yml
--- a/.github/workflows/jenkins-deploy.yml
+++ b/.github/workflows/jenkins-deploy.yml
@@ -79,7 +79,7 @@ jobs:
 
       - name: Trigger Jenkins Job
         run: |
-          curl -X POST "https://jenkinsdev.cdservice.genesis.global/buildByToken/buildWithParameters?token=${{ secrets.JENKINS_SECURITYTOKEN }}&job=AppDev-CI_CD/${{ inputs.product }}/${{ inputs.environment_level }}/product_${{ inputs.product }}_upgrade" \
+          response=$(curl -X POST "https://jenkinsdev.cdservice.genesis.global/buildByToken/buildWithParameters?token=${{ secrets.JENKINS_SECURITYTOKEN }}&job=AppDev-CI_CD/${{ inputs.product }}/${{ inputs.environment_level }}/product_${{ inputs.product }}_upgrade" \
             --data-urlencode "client=${{ inputs.CLIENT }}" \
             --data-urlencode "environment=${{ inputs.ENVIRONMENT }}" \
             --data-urlencode "hosts=${{ inputs.HOSTS }}" \
@@ -93,26 +93,39 @@ jobs:
             --data-urlencode "genesis_user=${{ inputs.GENESIS_USER }}" \
             --data-urlencode "environment_level=${{ inputs.environment_level }}" \
             --data-urlencode "product=${{ inputs.PRODUCT }}" \
-            --data-urlencode "repotype=${{ inputs.repotype }}"
+            --data-urlencode "repotype=${{ inputs.repotype }}" \
+            --silent --write-out "%{http_code}" --output /dev/null)
 
-      - name: Install jq
-        run: sudo dnf install -y jq
+          if [ "$response" -ne 201 ]; then
+            echo "Failed to trigger Jenkins job"
+            exit 1
+          fi
 
-      - name: Poll Jenkins for Job Status
+          # Extract Jenkins job queue URL
+          queue_url=$(curl -s -X POST "https://jenkinsdev.cdservice.genesis.global/buildByToken/buildWithParameters?token=${{ secrets.JENKINS_SECURITYTOKEN }}&job=AppDev-CI_CD/${{ inputs.product }}/${{ inputs.environment_level }}/product_${{ inputs.product }}_upgrade" --data-urlencode "client=${{ inputs.client }}" --data-urlencode "environment=${{ inputs.environment }}" --output /dev/null -I -L -w "%{url_effective}")
+
+          # Extracting job ID from queue URL
+          job_id=${queue_url##*/}
+          echo "Jenkins Job ID: $job_id"
+
+      - name: Poll Jenkins Job Status
+        id: poll_jenkins
         run: |
-          JOB_STATUS="null"
-          while [ "$JOB_STATUS" != "SUCCESS" ] && [ "$JOB_STATUS" != "FAILURE" ]; do
-            JOB_URL=$(curl -s "https://jenkinsdev.cdservice.genesis.global/buildByToken/buildWithParameters?token=${{ secrets.JENKINS_SECURITYTOKEN }}&job=AppDev-CI_CD/${{ inputs.product }}/lastBuild/api/json" | jq -r .url)
-            JOB_STATUS=$(curl -s "$JOB_URL/api/json" | jq -r .result)
-            echo "Current status: $JOB_STATUS"
-            if [ "$JOB_STATUS" == "SUCCESS" ]; then
+          while true; do
+            status=$(curl -s "https://jenkinsdev.cdservice.genesis.global/queue/item/$job_id/api/json" | jq -r '.executable.result')
+            echo "Current Status: $status"
+
+            if [ "$status" = "SUCCESS" ]; then
               echo "Jenkins job completed successfully."
-            elif [ "$JOB_STATUS" == "FAILURE" ]; then
+              break
+            elif [ "$status" = "FAILURE" ]; then
               echo "Jenkins job failed."
               exit 1
-            else
-              echo "Job is still running..."
-              sleep 10
+            elif [ "$status" = "ABORTED" ]; then
+              echo "Jenkins job was aborted."
+              exit 1
             fi
+
+            echo "Waiting for Jenkins job to complete..."
+            sleep 30
           done
-        
