test gradle project

diff --git a/.github/workflows/run-gradle-test-suite.yml b/.github/workflows/run-gradle-test-suite.yml
--- a/.github/workflows/run-gradle-test-suite.yml
+++ b/.github/workflows/run-gradle-test-suite.yml
@@ -168,19 +168,19 @@ jobs:
     #     # sudo chmod -R +rx ./${{ inputs.test-root-path }}/
           
           
-    - name: Run Gradle
-      shell: bash
-      run: |
-        export GENESIS_USER_PRIVATE_KEY="${{ secrets.GENESIS_USER_PRIVATE_KEY }}"       
+    # - name: Run Gradle
+    #   shell: bash
+    #   run: |
+    #     export GENESIS_USER_PRIVATE_KEY="${{ secrets.GENESIS_USER_PRIVATE_KEY }}"       
        
-        cd ${{ inputs.test-root-path }}
-        command="./gradlew clean test --stacktrace" 
-        eval $command | tee gradle.log
-        if grep -q "BUILD FAILED" gradle.log; then
-          exit 1
-        else
-          exit 0
-        fi
+    #     cd ${{ inputs.test-root-path }}
+    #     command="./gradlew clean test --stacktrace" 
+    #     eval $command | tee gradle.log
+    #     if grep -q "BUILD FAILED" gradle.log; then
+    #       exit 1
+    #     else
+    #       exit 0
+    #     fi
 
     - name: Run tests
       uses: gradle/gradle-build-action@v2
