changes in sonar

diff --git a/.github/workflows/sonar-update.yml b/.github/workflows/sonar-update.yml
--- a/.github/workflows/sonar-update.yml
+++ b/.github/workflows/sonar-update.yml
@@ -213,76 +213,76 @@ jobs:
           name: ${{ inputs.appuser }}-jacoco-report-html
           path: /opt/actions-runner/_work/platform-qa-automation/platform-qa-automation/${{ inputs.appuser }}/${{ inputs.appuser }}/bin/${{ inputs.appuser }}.html
 
-      - name: Set up JDK
-        uses: actions/setup-java@v4
-        with:
-          java-version: ${{ inputs.java_version }}
-          distribution: 'adopt'
+      # - name: Set up JDK
+      #   uses: actions/setup-java@v4
+      #   with:
+      #     java-version: ${{ inputs.java_version }}
+      #     distribution: 'adopt'
 
-      - name: Configure Node
-        if: ${{ !inputs.REGISTRY_URL  }}
-        uses: actions/setup-node@v2
-        with:
-          node-version: ${{ inputs.node_version }}
+      # - name: Configure Node
+      #   if: ${{ !inputs.REGISTRY_URL  }}
+      #   uses: actions/setup-node@v2
+      #   with:
+      #     node-version: ${{ inputs.node_version }}
 
-      - name: Configure Node if using JFROG npm packages
-        if: ${{ inputs.REGISTRY_URL }}
-        uses: actions/setup-node@v2
-        with:
-          node-version: ${{ inputs.node_version }}
-          registry-url: ${{ inputs.REGISTRY_URL }}
-          scope: ${{ inputs.SCOPE }}
+      # - name: Configure Node if using JFROG npm packages
+      #   if: ${{ inputs.REGISTRY_URL }}
+      #   uses: actions/setup-node@v2
+      #   with:
+      #     node-version: ${{ inputs.node_version }}
+      #     registry-url: ${{ inputs.REGISTRY_URL }}
+      #     scope: ${{ inputs.SCOPE }}
 
-      - name: Restore gradle.properties and setup
-        env:
-          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
-        working-directory: "./app-repo"
-        shell: bash
-        run: |
-          mkdir -p ~/.gradle/
-          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
-          echo "genesisArtifactoryUser=${{ secrets.JFROG_USERNAME }}" > ~/.gradle/gradle.properties
-          echo "genesisArtifactoryPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties
+      # - name: Restore gradle.properties and setup
+      #   env:
+      #     GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
+      #   working-directory: "./app-repo"
+      #   shell: bash
+      #   run: |
+      #     mkdir -p ~/.gradle/
+      #     echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
+      #     echo "genesisArtifactoryUser=${{ secrets.JFROG_USERNAME }}" > ~/.gradle/gradle.properties
+      #     echo "genesisArtifactoryPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties
 
-          echo "systemProp.org.gradle.internal.http.connectionTimeout=180000" >> ~/.gradle/gradle.properties
-          echo "systemProp.org.gradle.internal.http.socketTimeout=180000" >> ~/.gradle/gradle.properties
+      #     echo "systemProp.org.gradle.internal.http.connectionTimeout=180000" >> ~/.gradle/gradle.properties
+      #     echo "systemProp.org.gradle.internal.http.socketTimeout=180000" >> ~/.gradle/gradle.properties
 
-          echo "dockerUrl=genesisglobal-docker-internal.jfrog.io" >> ~/.gradle/gradle.properties
-          echo "dockerUsername=${{ secrets.JFROG_USERNAME }}" >> ~/.gradle/gradle.properties
-          echo "dockerPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties
-          echo "dockerEmail=platformmanageteam@genesis.global" >> ~/.gradle/gradle.properties
+      #     echo "dockerUrl=genesisglobal-docker-internal.jfrog.io" >> ~/.gradle/gradle.properties
+      #     echo "dockerUsername=${{ secrets.JFROG_USERNAME }}" >> ~/.gradle/gradle.properties
+      #     echo "dockerPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties
+      #     echo "dockerEmail=platformmanageteam@genesis.global" >> ~/.gradle/gradle.properties
 
-          echo "genesis-home=../.genesis-home" >> ~/.gradle/gradle.properties
-          echo "deploy-plugin-mode=local" >> ~/.gradle/gradle.properties
-          sudo chmod +x ./gradlew
-          sudo chmod +x ./${{ inputs.server-path }}/gradlew
-          sudo chmod -R +rx ./${{ inputs.server-path }}/
-          cat ~/.gradle/gradle.properties >>  ./gradle.properties
-          if [ -z "${{ inputs.repo-name }}" ]; then
-            echo "REPO_NAME=$(echo '${{ github.event.repository.name }}' | cut -d'-' -f1)" >> $GITHUB_ENV
-          else
-            echo "REPO_NAME=${{ inputs.repo-name }}" >> $GITHUB_ENV
-          fi
-          RELEASE_VERSION=$(echo "${{ inputs.version }}" | sed 's/\//-/g')
-          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
-          sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts
+      #     echo "genesis-home=../.genesis-home" >> ~/.gradle/gradle.properties
+      #     echo "deploy-plugin-mode=local" >> ~/.gradle/gradle.properties
+      #     sudo chmod +x ./gradlew
+      #     sudo chmod +x ./${{ inputs.server-path }}/gradlew
+      #     sudo chmod -R +rx ./${{ inputs.server-path }}/
+      #     cat ~/.gradle/gradle.properties >>  ./gradle.properties
+      #     if [ -z "${{ inputs.repo-name }}" ]; then
+      #       echo "REPO_NAME=$(echo '${{ github.event.repository.name }}' | cut -d'-' -f1)" >> $GITHUB_ENV
+      #     else
+      #       echo "REPO_NAME=${{ inputs.repo-name }}" >> $GITHUB_ENV
+      #     fi
+      #     RELEASE_VERSION=$(echo "${{ inputs.version }}" | sed 's/\//-/g')
+      #     echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
+      #     sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts
 
-      - name: Sonar Test
-        uses: gradle/gradle-build-action@v2
-        env:
-          SONAR_TOKEN: ${{ secrets.JENKINSGENESIS_SONAR }}
-        with:
-          arguments: test jacocoTestReport sonarqube --no-configuration-cache -Dsonar.token=${{env.SONAR_TOKEN}}
-          build-root-directory: ./app-repo/${{ inputs.server-path }}
-          cache-disabled: true
+      # - name: Sonar Test
+      #   uses: gradle/gradle-build-action@v2
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.JENKINSGENESIS_SONAR }}
+      #   with:
+      #     arguments: test jacocoTestReport sonarqube --no-configuration-cache -Dsonar.token=${{env.SONAR_TOKEN}}
+      #     build-root-directory: ./app-repo/${{ inputs.server-path }}
+      #     cache-disabled: true
 
-      - name: Verify JaCoCo Test Report
-        run: |
-          ls -l ./app-repo/${{ inputs.server-path }}/build/reports/jacoco/test/
-          test -f ./app-repo/${{ inputs.server-path }}/build/reports/jacoco/test/jacocoTestReport.xml && echo "JaCoCo Report Found" || echo "JaCoCo Report Missing"
+      # - name: Verify JaCoCo Test Report
+      #   run: |
+      #     ls -l ./app-repo/${{ inputs.server-path }}/build/reports/jacoco/test/
+      #     test -f ./app-repo/${{ inputs.server-path }}/build/reports/jacoco/test/jacocoTestReport.xml && echo "JaCoCo Report Found" || echo "JaCoCo Report Missing"
 
-      - name: Upload JaCoCo Report as Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: server-jacoco-xml-test-report-${{ inputs.appuser }}
-          path: ./app-repo/${{ inputs.server-path }}/build/reports/jacoco/test/jacocoTestReport.xml
+      # - name: Upload JaCoCo Report as Artifact
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: server-jacoco-xml-test-report-${{ inputs.appuser }}
+      #     path: ./app-repo/${{ inputs.server-path }}/build/reports/jacoco/test/jacocoTestReport.xml
