sonar changes

diff --git a/.github/workflows/sonar-update.yml b/.github/workflows/sonar-update.yml
--- a/.github/workflows/sonar-update.yml
+++ b/.github/workflows/sonar-update.yml
@@ -129,7 +129,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           repository: genesislcap/fical
-          ref: develop
+          ref: sonar
           token: ${{ secrets.GHA_TOKEN }}
           path: app-repo
           fetch-depth: 0
@@ -139,36 +139,36 @@ jobs:
           echo "hostname: ${{ inputs.hostname }}"
           echo "genesis_user: ${{ inputs.genesis_user }}"
 
-      - name: Trigger Jenkins Job
-        run: |
-          curl -X POST "https://jenkinsdev.cdservice.genesis.global/buildByToken/buildWithParameters?token=${{ secrets.JENKINS_SECURITYTOKEN }}&job=AppDev-CI_CD/PLT_QA_Automation/sonar-update" \
-            --data-urlencode "host_name=${{ inputs.hostname }}" \
-            --data-urlencode "appuser=${{ inputs.appuser }}"
+      # - name: Trigger Jenkins Job
+      #   run: |
+      #     curl -X POST "https://jenkinsdev.cdservice.genesis.global/buildByToken/buildWithParameters?token=${{ secrets.JENKINS_SECURITYTOKEN }}&job=AppDev-CI_CD/PLT_QA_Automation/sonar-update" \
+      #       --data-urlencode "host_name=${{ inputs.hostname }}" \
+      #       --data-urlencode "appuser=${{ inputs.appuser }}"
 
-      - name: Poll Jenkins for Job Status
-        run: |
-          JOB_STATUS=""
-          JOB_URL="https://jenkinsdev.cdservice.genesis.global/job/AppDev-CI_CD/job/PLT_QA_Automation/job/sonar-update/lastBuild/api/json"
+      # - name: Poll Jenkins for Job Status
+      #   run: |
+      #     JOB_STATUS=""
+      #     JOB_URL="https://jenkinsdev.cdservice.genesis.global/job/AppDev-CI_CD/job/PLT_QA_Automation/job/sonar-update/lastBuild/api/json"
 
-          while [ -z "$JOB_STATUS" ] || [ "$JOB_STATUS" == "null" ]; do
-            RESPONSE=$(curl -s -u "purna.sakhamuri:${{ secrets.JENKINS_TOKEN }}" "$JOB_URL")
-            JOB_STATUS=$(echo "$RESPONSE" | jq -r .result)
-            echo "Current status: $JOB_STATUS"
+      #     while [ -z "$JOB_STATUS" ] || [ "$JOB_STATUS" == "null" ]; do
+      #       RESPONSE=$(curl -s -u "purna.sakhamuri:${{ secrets.JENKINS_TOKEN }}" "$JOB_URL")
+      #       JOB_STATUS=$(echo "$RESPONSE" | jq -r .result)
+      #       echo "Current status: $JOB_STATUS"
 
-            if [ "$JOB_STATUS" == "SUCCESS" ]; then
-              echo "Jenkins job completed successfully."
-              exit 0
-            elif [ "$JOB_STATUS" == "FAILURE" ]; then
-              echo "Jenkins job failed."
-              exit 1
-            elif [ "$JOB_STATUS" == "ABORTED" ]; then
-              echo "Jenkins job was aborted."
-              exit 2
-            elif [ -z "$JOB_STATUS" ] || [ "$JOB_STATUS" == "null" ]; then
-              echo "Job is still running..."
-              sleep 10
-            fi
-          done
+      #       if [ "$JOB_STATUS" == "SUCCESS" ]; then
+      #         echo "Jenkins job completed successfully."
+      #         exit 0
+      #       elif [ "$JOB_STATUS" == "FAILURE" ]; then
+      #         echo "Jenkins job failed."
+      #         exit 1
+      #       elif [ "$JOB_STATUS" == "ABORTED" ]; then
+      #         echo "Jenkins job was aborted."
+      #         exit 2
+      #       elif [ -z "$JOB_STATUS" ] || [ "$JOB_STATUS" == "null" ]; then
+      #         echo "Job is still running..."
+      #         sleep 10
+      #       fi
+      #     done
 
       - name: Download and Extract JaCoCo CLI
         run: |
@@ -207,18 +207,6 @@ jobs:
           mkdir -p app-repo/reports/jacoco/test
           mv ${{ inputs.appuser }}/${{ inputs.appuser }}/bin/jacocoTestReport.xml app-repo/reports/jacoco/test/
           ls -l
-
-      # - name: Trigger SonarCloud analysis
-      #   run: |
-      #     sudo yum update -y
-      #     sudo yum install -y java-17-amazon-corretto-devel
-
-      #     sonar-scanner \
-      #       -Dsonar.projectKey=genesislcap_fical \
-      #       -Dsonar.organization=genesislcap \
-      #       -Dsonar.login=${{ secrets.JENKINSGENESIS_SONAR }} \
-      #       -Dsonar.coverage.jacoco.xmlReportPaths=app-repo/reports/jacoco/test/jacocoTestReport.xml \
-      #       -Dsonar.host.url=https://sonarcloud.io
 
       - name: Upload JaCoCo Coverage Report
         uses: actions/upload-artifact@v3
@@ -280,7 +268,7 @@ jobs:
           echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
           sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts
 
-      - name: Server Build
+      - name: Sonar Test
         uses: gradle/gradle-build-action@v2
         env:
           SONAR_TOKEN: ${{ secrets.JENKINSGENESIS_SONAR }}
